spring:
  datasource:
    url: jdbc:postgresql://localhost:1984/ifa-database
    username: postgres
    password: Banza!1984
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none   # usamos schema.sql
    show-sql: true
    properties:
      hibernate:
        # format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8081
